$ErrorActionPreference = "Stop"

Write-Host "🚀 Installing mobaXMan for Windows..." -ForegroundColor Cyan

# NOTE: Change 'yourusername/mobaXMan' to your actual GitHub repository!
$repo = "manHax/mobaXMan"
$releaseUrl = "https://api.github.com/repos/$repo/releases/latest"

Write-Host "🔍 Finding latest release..."
try {
    $release = Invoke-RestMethod -Uri $releaseUrl
    $asset = $release.assets | Where-Object { $_.name -match 'Setup.*\.exe$' -or $_.name -match '\.exe$' } | Select-Object -First 1
} catch {
    Write-Error "Failed to fetch release info. Have you published a GitHub Release?"
    exit 1
}

if (-not $asset) {
    Write-Error "❌ Error: Could not find a .exe installer in the latest release of $repo."
    exit 1
}

$installerPath = Join-Path $env:TEMP $asset.name
Write-Host "📥 Downloading $($asset.browser_download_url)..." -ForegroundColor Yellow
Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $installerPath

Write-Host "💻 Running installer silently..." -ForegroundColor Yellow
# /S is the standard silent install flag for NSIS installers generated by electron-builder
Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait

Write-Host "✅ Installation complete! You can find mobaXMan in your Start Menu." -ForegroundColor Green
